openapi: '3.1.0'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /test:
    get:
      tags:
        -  Hello
      operationId: GetTest
      summary: get a test
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                discriminator:
                  propertyName: asset_type
                  mapping:
                    native: '#/components/schemas/BalanceLineNative'
                    credit_alphanum4: '#/components/schemas/BalanceLineAsset'
                    credit_alphanum12: '#/components/schemas/BalanceLineAsset'
                    liquidity_pool_shares: '#/components/schemas/BalanceLineLiquidityPool'
                oneOf:
                  - $ref: '#/components/schemas/BalanceLineNative'
                  - $ref: '#/components/schemas/BalanceLineAsset'
                  - $ref: '#/components/schemas/BalanceLineLiquidityPool'
components:
  schemas:
    ThingOne:
      x-tags:
        - Hello
      type: object
      description: the top thing
      properties:
        hello:
          type: string
          description: a greeting
        world:
          $ref: '#/components/schemas/ThingOne'
    BalanceLineNative:
      x-tags:
        - Hello
      type: object
      properties:
        balance:
          $ref: '#/components/schemas/currency'
        buying_liabilities:
          $ref: '#/components/schemas/currency'
        selling_liabilities:
          $ref: '#/components/schemas/currency'
        asset_type:
          type: string
          enum: [native]
      required:
        - balance
        - buying_liabilities
        - selling_liabilities
        - asset_type
    BalanceLineAsset:
      x-tags:
        - Hello
      type: object
      properties:
        balance:
          $ref: '#/components/schemas/currency'
        limit:
          $ref: '#/components/schemas/currency'
        buying_liabilities:
          $ref: '#/components/schemas/currency'
        selling_liabilities:
          $ref: '#/components/schemas/currency'
        sponsor:
          $ref: '#/components/schemas/address'
        last_modified_ledger:
            $ref: '#/components/schemas/last_modified_ledger'
        is_authorized:
          type: boolean
        is_authorized_to_maintain_liabilities:
          type: boolean
        is_clawback_enabled:
          type: boolean
        asset_type:
          type: string
          enum: [credit_alphanum4, credit_alphanum12]
        asset_code:
          type: string
        asset_issuer:
          $ref: '#/components/schemas/address'
      required:
        - balance
        - limit
        - asset_type
        - asset_code
        - asset_issuer
        - buying_liabilities
        - selling_liabilities
        - last_modified_ledger
        - is_authorized
        - is_authorized_to_maintain_liabilities
    BalanceLineLiquidityPool:
      x-tags:
        - Hello
      type: object
      properties:
        balance:
          $ref: '#/components/schemas/currency'
        liquidity_pool_id:
          type: string
        limit:
          $ref: '#/components/schemas/currency'
        last_modified_ledger:
            $ref: '#/components/schemas/last_modified_ledger'
        sponsor:
          $ref: '#/components/schemas/address'
        is_authorized:
          type: boolean
        is_authorized_to_maintain_liabilities:
          type: boolean
        asset_type:
          type: string
          enum:
            - liquidity_pool_shares
      required:
        - liquidity_pool_id
        - balance
        - limit
        - last_modified_ledger
        - is_authorized
        - is_authorized_to_maintain_liabilities
        - asset_type
    currency:
      type: string
      pattern: '[0-9]+\.[0-9]{7}'
    address:
      type: string
      pattern: "G[A-Z0-9]{55}"
    last_modified_ledger:
      type: integer
      format: uint32
